# Variable
@baseUrl = http://localhost:3333
@roomId = {{getRooms.response.body.$.[1].id}}

# Health check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "Test Room",
    "description": "This is a Test Room"
}

###
# @name getRoomQuestions
# Get question by roomId
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create question
# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
    "question": "What is the difference between X and Y?"
}